#!/usr/bin/env bash
# backup.sh — Main backup script for db-mac-backup
# Sources lib/*.sh, reads .backup-config, dispatches to category handlers.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/lib/utils.sh"
source "$SCRIPT_DIR/lib/brew.sh"

# -----------------------------------------------------------------------
# Config generation
# -----------------------------------------------------------------------

generate_default_config() {
    local config_file=".backup-config"
    local home
    home="$(eval echo ~$USER)"
    local default_dest="$home/OneDrive/db-mac-backup"
    local default_git_root="$home/projects"

    # Try to detect existing GPG key
    local gpg_key=""
    if command -v gpg &>/dev/null; then
        gpg_key=$(gpg --list-secret-keys --keyid-format long 2>/dev/null | grep -m1 "^sec" | awk '{print $2}' | awk -F'/' '{print $NF}')
    fi

    # Try to detect dotfiles apps
    local dotfiles_apps=""
    if [[ -d "$home/.config" ]]; then
        dotfiles_apps=$(find "$home/.config" -mindepth 1 -maxdepth 1 -type d ! -name '.*' 2>/dev/null | xargs -I{} basename {} | sort | tr '\n' ' ')
    fi

    cat > "$config_file" <<EOF
# db-mac-backup configuration
# Generated by backup.sh --generate-config
# Edit this file manually or run ./wizard for interactive setup.

MODE=backup

BACKUP_DEST=$default_dest

# Categories
BACKUP_HOMEBREW=true
RESTORE_HOMEBREW=true
BACKUP_GIT=true
RESTORE_GIT=true
BACKUP_DOTFILES=true
RESTORE_DOTFILES=true
BACKUP_APPS=false
RESTORE_APPS=false
BACKUP_SYSTEM=false
RESTORE_SYSTEM=false

# GPG encryption key (long key ID)
# GPG_KEY=$gpg_key

# Dotfiles apps (space-separated)
# DOTFILES_APPS=$dotfiles_apps

# Root directory for git repo scan (all .git repos inside are backed up automatically)
GIT_ROOT=$default_git_root
EOF

    log_info "Generated default configuration: $config_file"
    log_info "Edit $config_file to customize, then run ./backup.sh or ./restore.sh"
}

# Parse command-line flags
DRY_RUN=false
SPECIFIC_CATEGORY=""
MAX_REPOS=""
BACKUP_DEST_OVERRIDE=""
GPG_KEY_OVERRIDE=""
DOTFILES_APPS_OVERRIDE=""
GIT_ROOT_OVERRIDE=""
GENERATE_CONFIG=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --mode)
            MODE_OVERRIDE="$2"
            shift 2
            ;;
        --category|--categories)
            SPECIFIC_CATEGORY="$2"
            shift 2
            ;;
        --dest)
            BACKUP_DEST_OVERRIDE="$2"
            shift 2
            ;;
        --gpg-key)
            GPG_KEY_OVERRIDE="$2"
            shift 2
            ;;
        --dotfiles-apps)
            DOTFILES_APPS_OVERRIDE="$2"
            shift 2
            ;;
        --git-root)
            GIT_ROOT_OVERRIDE="$2"
            shift 2
            ;;
        --max-repos)
            MAX_REPOS="$2"
            shift 2
            ;;
        --generate-config)
            GENERATE_CONFIG=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --dry-run          Show what would be done without executing"
            echo "  --mode backup|restore  Set mode (overrides config)"
            echo "  --category <name>  Run only this category (homebrew, git, dotfiles, apps, system)"
            echo "  --dest <path>      Override backup/restore destination"
            echo "  --gpg-key <key>    Override GPG key for encryption"
            echo "  --dotfiles-apps <apps>  Space-separated list of dotfiles apps"
            echo "  --git-root <path>       Root directory to scan for git repos (default: from config)"
            echo "  --max-repos <n>    Limit git backup to N repos (for testing)"
            echo "  --generate-config  Generate a default .backup-config file"
            echo "  --help, -h         Show this help"
            exit 0
            ;;
        *)
            die "Unknown option: $1"
            ;;
    esac
done

# Generate default config if requested
if [[ "$GENERATE_CONFIG" == true ]]; then
    generate_default_config
    exit 0
fi

export DRY_RUN

# Load config
if ! load_config; then
    die "No configuration found. Run ./wizard.sh first."
fi

# Apply CLI overrides to config variables
if [[ -n "${MODE_OVERRIDE:-}" ]]; then
    MODE="$MODE_OVERRIDE"
fi
if [[ -n "${BACKUP_DEST_OVERRIDE:-}" ]]; then
    BACKUP_DEST="$BACKUP_DEST_OVERRIDE"
fi
if [[ -n "${GPG_KEY_OVERRIDE:-}" ]]; then
    GPG_KEY="$GPG_KEY_OVERRIDE"
fi
if [[ -n "${DOTFILES_APPS_OVERRIDE:-}" ]]; then
    DOTFILES_APPS="$DOTFILES_APPS_OVERRIDE"
fi
if [[ -n "${GIT_ROOT_OVERRIDE:-}" ]]; then
    GIT_ROOT="$GIT_ROOT_OVERRIDE"
fi

# Resolve destination
DEST="$(get_backup_dest)"
# Expand ~ to $HOME
DEST="${DEST/#\~/$HOME}"

# Ensure destination directory exists
mkdir -p "$DEST"

log_info "============================================"
log_info "  db-mac-backup — Backup"
log_info "============================================"
log_info "Destination: $DEST"
if [[ "$DRY_RUN" == "true" ]]; then
    log_info "[DRY-RUN MODE] Nothing will be modified."
fi
log_info ""

# -----------------------------------------------------------------------
# Category dispatch
# -----------------------------------------------------------------------

backup_homebrew() {
    if [[ "${BACKUP_HOMEBREW:-false}" != "true" ]]; then
        log_info "Homebrew backup: SKIPPED (not enabled in config)"
        return
    fi

    brew_backup "$DEST"
}

backup_git() {
    if [[ "${BACKUP_GIT:-false}" != "true" ]]; then
        log_info "Git backup: SKIPPED (not enabled in config)"
        return
    fi

    local git_dest="$DEST/git"
    mkdir -p "$git_dest"

    # Resolve GIT_ROOT (expand ~)
    local scan_root="${GIT_ROOT:-$HOME/projects}"
    scan_root="${scan_root/#\~/$HOME}"

    if [[ ! -d "$scan_root" ]]; then
        log_warn "Git backup: GIT_ROOT directory not found: $scan_root"
        return
    fi

    log_info "Git: scanning $scan_root for repos..."

    # Scan GIT_ROOT for all .git directories, skipping build/dep dirs
    local repos_to_backup=()
    while IFS= read -r git_dir; do
        repos_to_backup+=("$(dirname "$git_dir")")
    done < <(find "$scan_root" \
        \( -name 'node_modules' -o -name '__pycache__' -o -name 'dist' \
           -o -name 'build' -o -name '.terraform' -o -name '.venv' \
           -o -name 'venv' -o -name '.cache' -o -name '.parcel-cache' \
           -o -name 'target' -o -name 'vendor' -o -name 'coverage' \
        \) -type d -prune \
        -o -name '.git' -type d -print \
        2>/dev/null | sort)

    if [[ ${#repos_to_backup[@]} -eq 0 ]]; then
        log_info "Git backup: No repos found in ~/projects"
        return
    fi

    local total=${#repos_to_backup[@]}
    local count=0

    for repo in "${repos_to_backup[@]}"; do
        count=$((count + 1))

        # Limit to MAX_REPOS if specified (for testing)
        if [[ -n "$MAX_REPOS" ]] && [[ $count -gt $MAX_REPOS ]]; then
            log_info "Git: limiting to $MAX_REPOS repos (skipping remaining $((total - count)) repos)"
            break
        fi

        if [[ ! -d "$repo/.git" ]]; then
            continue
        fi

        # Use path relative to GIT_ROOT to preserve directory structure
        local repo_rel
        repo_rel="${repo#"$scan_root/"}"
        local repo_name
        repo_name="$(basename "$repo")"
        log_progress "Git: [$count/$total] backing up $repo_rel..."
        local repo_backup_dir="$git_dest/$repo_rel"
        mkdir -p "$repo_backup_dir"

        log_progress "Git: backing up $repo_name..."

        # Backup .git/config (contains remotes)
        run_or_dry_run "Git: rsyncing .git/config for $repo_name" \
            "cp '$repo/.git/config' '$repo_backup_dir/config'"

        # Backup .git/ directory structure (metadata only, exclude objects/refs)
        run_or_dry_run "Git: rsyncing .git/ structure for $repo_name" \
            "rsync -av --exclude='objects' --exclude='refs' --exclude='logs' \
             '$repo/.git/' '$repo_backup_dir/.git/'"

        # Generate dirty patches
        local patches_dir="$repo_backup_dir/patches"
        mkdir -p "$patches_dir"

        # Staged changes
        if git -C "$repo" diff --staged --quiet 2>/dev/null; then
            : # no staged changes
        else
            run_or_dry_run "Git: creating staged patch for $repo_name" \
                "git -C '$repo' diff --staged > '$patches_dir/staged.diff'"
        fi

        # Unstaged changes
        if git -C "$repo" diff --quiet 2>/dev/null; then
            : # no unstaged changes
        else
            run_or_dry_run "Git: creating unstaged patch for $repo_name" \
                "git -C '$repo' diff > '$patches_dir/unstaged.diff'"
        fi

        # Save repo metadata
        local metadata_dir="$repo_backup_dir/metadata"
        mkdir -p "$metadata_dir"
        run_or_dry_run "Git: saving remotes for $repo_name" \
            "git -C '$repo' remote -v > '$metadata_dir/remotes.txt'"
        run_or_dry_run "Git: saving branches for $repo_name" \
            "git -C '$repo' branch -a > '$metadata_dir/branches.txt'"
    done
}

backup_dotfiles() {
    if [[ "${BACKUP_DOTFILES:-false}" != "true" ]]; then
        log_info "Dotfiles backup: SKIPPED (not enabled in config)"
        return
    fi

    local dotfiles_dest="$DEST/dotfiles"
    mkdir -p "$dotfiles_dest"

    log_progress "Dotfiles: backing up shell configs..."

    # Always-backup shell configs
    for f in .zshrc .zshenv .zprofile .bashrc .bash_profile .gitconfig .gitignore_global; do
        if [[ -f "$HOME/$f" ]]; then
            run_or_dry_run "Dotfiles: rsyncing $f" \
                "cp '$HOME/$f' '$dotfiles_dest/$f'"
        fi
    done

    # Always-backup .ssh/ (will be encrypted if GPG key configured)
    if [[ -d "$HOME/.ssh" ]]; then
        local ssh_dest="$dotfiles_dest/.ssh"
        mkdir -p "$ssh_dest"

        if [[ -n "${GPG_KEY:-}" ]]; then
            log_info "Dotfiles: encrypting .ssh/ with GPG key $GPG_KEY"
            # Backup and encrypt
            run_or_dry_run "Dotfiles: rsyncing .ssh/ for encryption" \
                "rsync -av --exclude='*.pub' '$HOME/.ssh/' '$ssh_dest/'"
            # Encrypt each private key file
            for key_file in "$ssh_dest"/*; do
                if [[ -f "$key_file" ]] && [[ ! "$key_file" == *.pub ]]; then
                    run_or_dry_run "Dotfiles: encrypting $(basename "$key_file")" \
                        "gpg --batch --yes --trust-model always --recipient '$GPG_KEY' --encrypt --output '${key_file}.gpg' '$key_file' && rm '$key_file'"
                fi
            done
        else
            run_or_dry_run "Dotfiles: rsyncing .ssh/" \
                "rsync -av '$HOME/.ssh/' '$ssh_dest/'"
        fi
    fi

    # Always-backup .gnupg/ (will be encrypted if GPG key configured)
    if [[ -d "$HOME/.gnupg" ]]; then
        local gnupg_dest="$dotfiles_dest/.gnupg"
        mkdir -p "$gnupg_dest"

        if [[ -n "${GPG_KEY:-}" ]]; then
            log_info "Dotfiles: encrypting .gnupg/ with GPG key $GPG_KEY"
            run_or_dry_run "Dotfiles: rsyncing .gnupg/ for encryption" \
                "rsync -av '$HOME/.gnupg/' '$gnupg_dest/'"
            # Encrypt key files
            for key_file in "$gnupg_dest"/*; do
                if [[ -f "$key_file" ]]; then
                    run_or_dry_run "Dotfiles: encrypting $(basename "$key_file")" \
                        "gpg --batch --yes --trust-model always --recipient '$GPG_KEY' --encrypt --output '${key_file}.gpg' '$key_file' && rm '$key_file'"
                fi
            done
        else
            run_or_dry_run "Dotfiles: rsyncing .gnupg/" \
                "rsync -av '$HOME/.gnupg/' '$gnupg_dest/'"
        fi
    fi

    # Conditionally-backup selected apps from ~/.config/
    if [[ -n "${DOTFILES_APPS:-}" ]]; then
        log_progress "Dotfiles: backing up selected app configs..."
        for app in $DOTFILES_APPS; do
            local app_dir="$HOME/.config/$app"
            if [[ -d "$app_dir" ]]; then
                local app_dest="$dotfiles_dest/.config/$app"
                mkdir -p "$(dirname "$app_dest")"
                run_or_dry_run "Dotfiles: rsyncing $app from ~/.config/" \
                    "rsync -av '$app_dir/' '$app_dest/'"
            fi
        done
    fi

    # Conditionally-backup selected apps from ~/Library/Application Support/
    if [[ -n "${DOTFILES_APPS:-}" ]]; then
        for app in $DOTFILES_APPS; do
            local app_dir="$HOME/Library/Application Support/$app"
            if [[ -d "$app_dir" ]]; then
                local app_dest="$dotfiles_dest/app-support/$app"
                mkdir -p "$(dirname "$app_dest")"
                run_or_dry_run "Dotfiles: rsyncing $app from Application Support" \
                    "rsync -av '$app_dir/' '$app_dest/'"
            fi
        done
    fi
}

backup_apps() {
    if [[ "${BACKUP_APPS:-false}" != "true" ]]; then
        log_info "Apps backup: SKIPPED (not enabled in config)"
        return
    fi

    log_info "Apps backup: Not yet implemented (Slice 5)"
}

backup_system() {
    if [[ "${BACKUP_SYSTEM:-false}" != "true" ]]; then
        log_info "System backup: SKIPPED (not enabled in config)"
        return
    fi

    log_info "System backup: Not yet implemented (Slice 5)"
}

# -----------------------------------------------------------------------
# Main dispatch
# -----------------------------------------------------------------------

run_backup() {
    local category="$1"
    case "$category" in
        homebrew) backup_homebrew ;;
        git)      backup_git ;;
        dotfiles) backup_dotfiles ;;
        apps)     backup_apps ;;
        system)   backup_system ;;
        *)        log_error "Unknown category: $category" ;;
    esac
}

if [[ -n "$SPECIFIC_CATEGORY" ]]; then
    # Run only the specified category
    run_backup "$SPECIFIC_CATEGORY"
else
    # Run all enabled categories
    for category in homebrew git dotfiles apps system; do
        run_backup "$category"
    done
fi

log_info ""
log_info "============================================"
log_info "  Backup complete!"
log_info "============================================"
