#!/usr/bin/env node

import * as p from '@clack/prompts';
import { execSync } from 'child_process';
import { homedir } from 'os';
import { join } from 'path';
import { writeFileSync, readFileSync, existsSync, readdirSync, statSync } from 'fs';

const HOME = homedir();
const CONFIG_FILE = '.backup-config';
const DEFAULT_DEST = join(HOME, 'OneDrive', 'db-mac-backup');
const DEFAULT_GIT_ROOT = join(HOME, 'projects');

// ---------------------------------------------------------------------------
// Load existing config
// ---------------------------------------------------------------------------

function loadExistingConfig() {
  const cfg = {
    dest: DEFAULT_DEST,
    categories: ['homebrew', 'git', 'dotfiles'],
    gpgKey: '',
    dotfilesApps: [],
    gitRoot: DEFAULT_GIT_ROOT,
  };

  if (!existsSync(CONFIG_FILE)) return cfg;

  try {
    const text = readFileSync(CONFIG_FILE, 'utf-8');
    for (const line of text.split('\n')) {
      const trimmed = line.trim();
      if (trimmed.startsWith('#') || !trimmed.includes('=')) continue;
      const [key, ...rest] = trimmed.split('=');
      const val = rest.join('=').trim();

      switch (key.trim()) {
        case 'BACKUP_DEST':          cfg.dest = val; break;
        case 'GPG_KEY':              cfg.gpgKey = val; break;
        case 'DOTFILES_APPS':        cfg.dotfilesApps = val.split(/\s+/).filter(Boolean); break;
        case 'GIT_ROOT':             cfg.gitRoot = val; break;
        case 'BACKUP_HOMEBREW':      if (val === 'false') cfg.categories = cfg.categories.filter(c => c !== 'homebrew'); break;
        case 'BACKUP_GIT':           if (val === 'false') cfg.categories = cfg.categories.filter(c => c !== 'git'); break;
        case 'BACKUP_DOTFILES':      if (val === 'false') cfg.categories = cfg.categories.filter(c => c !== 'dotfiles'); break;
        case 'BACKUP_APPS':          if (val === 'true')  cfg.categories.push('apps'); break;
        case 'BACKUP_SYSTEM':        if (val === 'true')  cfg.categories.push('system'); break;
      }
    }
  } catch {
    // fallback to defaults
  }

  return cfg;
}

// ---------------------------------------------------------------------------
// Scanners
// ---------------------------------------------------------------------------

function scanGpgKeys() {
  try {
    const output = execSync(
      "gpg --list-secret-keys --keyid-format long 2>/dev/null",
      { encoding: 'utf-8' }
    );
    const keys = [];
    const lines = output.split('\n');
    let currentKey = null;

    for (const line of lines) {
      // Match: sec   rsa4096/866E2BD1777473E9 2020-02-28 [SC]
      const secMatch = line.match(/^sec\s+\w+\/([A-F0-9]+)\s/);
      const uidMatch = line.match(/^uid\s+(.*)/);

      if (secMatch) {
        currentKey = { id: secMatch[1], uid: '' };
        keys.push(currentKey);
      } else if (uidMatch && currentKey) {
        currentKey.uid = uidMatch[1].trim();
      }
    }

    return keys.filter(k => k.id && k.uid);
  } catch {
    return [];
  }
}

function scanDotfilesApps() {
  const apps = new Set();

  const configDir = join(HOME, '.config');
  if (existsSync(configDir)) {
    for (const entry of readdirSync(configDir)) {
      if (entry.startsWith('.')) continue;
      try {
        const s = statSync(join(configDir, entry));
        if (s.isDirectory()) apps.add(entry);
      } catch { /* skip unreadable */ }
    }
  }

  const appSupportDir = join(HOME, 'Library', 'Application Support');
  if (existsSync(appSupportDir)) {
    for (const entry of readdirSync(appSupportDir)) {
      if (entry.startsWith('.')) continue;
      try {
        const s = statSync(join(appSupportDir, entry));
        if (s.isDirectory()) apps.add(entry);
      } catch { /* skip unreadable */ }
    }
  }

  return Array.from(apps).sort();
}

// ---------------------------------------------------------------------------
// Config generation
// ---------------------------------------------------------------------------

function generateConfig(dest, categories, gpgKey, dotfilesApps, gitRoot) {
  const lines = [
    '# db-mac-backup configuration',
    '# Generated by wizard',
    '',
    'MODE=backup',
    '',
    `BACKUP_DEST=${dest}`,
    '',
    '# Categories',
  ];

  const allCats = ['homebrew', 'git', 'dotfiles', 'apps', 'system'];
  for (const cat of allCats) {
    const enabled = categories.includes(cat);
    lines.push(`BACKUP_${cat.toUpperCase()}=${enabled}`);
    lines.push(`RESTORE_${cat.toUpperCase()}=${enabled}`);
  }

  lines.push('');
  lines.push('# GPG encryption key (long key ID)');
  if (gpgKey) {
    lines.push(`GPG_KEY=${gpgKey}`);
  } else {
    lines.push('# GPG_KEY=');
  }

  lines.push('');
  lines.push('# Dotfiles apps (space-separated)');
  if (dotfilesApps.length > 0) {
    lines.push(`DOTFILES_APPS=${dotfilesApps.join(' ')}`);
  } else {
    lines.push('# DOTFILES_APPS=');
  }

  lines.push('');
  lines.push('# Root directory for git repo scan (all .git repos inside are backed up automatically)');
  lines.push(`GIT_ROOT=${gitRoot}`);

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Main wizard
// ---------------------------------------------------------------------------

async function main() {
  p.intro('db-mac-backup Configuration Wizard');

  // Load existing config for initial values
  const existing = loadExistingConfig();
  if (existsSync(CONFIG_FILE)) {
    p.log.info(`Loaded existing config from ${CONFIG_FILE}`);
  }

  // Step 1: Destination
  const dest = await p.text({
    message: 'Backup destination:',
    initialValue: existing.dest,
    validate: (value) => {
      if (!value.trim()) return 'Destination is required';
    },
  });

  if (p.isCancel(dest)) { p.cancel('Wizard cancelled.'); process.exit(0); }

  // Step 2: Categories
  const categories = await p.multiselect({
    message: 'Select categories to backup/restore:',
    options: [
      { value: 'homebrew', label: 'Homebrew (Brewfile)' },
      { value: 'git',      label: 'Git repos (structure + remotes)' },
      { value: 'dotfiles', label: 'Dotfiles + app configs' },
      { value: 'apps',     label: 'App configurations (not yet implemented)' },
      { value: 'system',   label: 'System settings (not yet implemented)' },
    ],
    initialValues: existing.categories,
    required: true,
  });

  if (p.isCancel(categories)) { p.cancel('Wizard cancelled.'); process.exit(0); }

  // Step 3: GPG key
  const gpgKeys = scanGpgKeys();
  let gpgKey = existing.gpgKey;

  if (gpgKeys.length === 0) {
    p.log.warn('No GPG secret keys found. Encryption will be skipped.');
    p.log.info('Create one with: gpg --full-generate-key');
  } else {
    const selectedKey = await p.select({
      message: 'Select GPG key for encryption (or skip):',
      options: [
        { value: '', label: '(skip encryption)', hint: 'No encryption' },
        ...gpgKeys.map(k => ({
          value: k.id,
          label: k.id,
          hint: k.uid,
        })),
      ],
      initialValue: existing.gpgKey || '',
    });

    if (!p.isCancel(selectedKey)) {
      gpgKey = selectedKey;
    }
  }

  // Step 4: Dotfiles apps (only if dotfiles category selected)
  let dotfilesApps = existing.dotfilesApps;
  if (categories.includes('dotfiles')) {
    const spinner = p.spinner();
    spinner.start('Scanning for dotfiles apps...');
    let apps = [];
    try {
      apps = scanDotfilesApps();
      spinner.stop(`Found ${apps.length} app configs.`);
    } catch (err) {
      spinner.stop('Scan failed.');
      p.log.error(`Error scanning dotfiles: ${err.message}`);
    }

    if (apps.length === 0) {
      p.log.info('No dotfiles apps found.');
    } else {
      const selected = await p.multiselect({
        message: 'Select dotfiles apps to backup:',
        options: apps.map(a => ({ value: a, label: a })),
        initialValues: existing.dotfilesApps.length > 0
          ? existing.dotfilesApps.filter(a => apps.includes(a))
          : apps,
        required: false,
      });

      if (!p.isCancel(selected)) {
        dotfilesApps = selected;
      }
    }
  }

  // Step 5: Git root directory (only if git category selected)
  let gitRoot = existing.gitRoot;
  if (categories.includes('git')) {
    const inputGitRoot = await p.text({
      message: 'Root directory for git repo scan:',
      initialValue: existing.gitRoot,
      hint: 'All git repos inside this directory will be backed up automatically',
      validate: (value) => {
        if (!value.trim()) return 'Git root directory is required';
        const expanded = value.replace(/^~/, HOME);
        if (!existsSync(expanded)) return `Directory not found: ${value}`;
      },
    });

    if (!p.isCancel(inputGitRoot)) {
      gitRoot = inputGitRoot;
    }
  }

  // Step 6: Preview & Save
  const configContent = generateConfig(dest, categories, gpgKey, dotfilesApps, gitRoot);

  p.note(configContent, 'Config preview');

  const save = await p.confirm({
    message: 'Save configuration?',
    initialValue: true,
  });

  if (p.isCancel(save) || save === false) {
    p.cancel('Configuration not saved.');
    process.exit(0);
  }

  writeFileSync(CONFIG_FILE, configContent, 'utf-8');
  p.outro(`✓ Configuration saved to ${CONFIG_FILE}\n\n  Run ./backup.sh or ./restore.sh to proceed.`);
}

main().catch((err) => {
  p.log.error(err.message);
  process.exit(1);
});
